version: 2
jobs:
  test:
    docker:
      - image: mhart/alpine-node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: cd modules/service-juno && docker build -t findmyrecords/service-juno .
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push findmyrecords/service-juno
      - run: cd modules/service-redeye && docker build -t findmyrecords/service-redeye .
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push findmyrecords/service-redeye
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy